version: "2.2"

services:
  es01:
    image: repo-nexus.kavosh.org:8080/elasticsearch:8.7.1
    container_name: es01
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - /data/elastic/data_es01:/usr/share/elasticsearch/data
    ports:
      - 9300:9300
      - 9200:9200
    environment:
      - node.name=es01
      # - cluster.name=singe-node
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
      # - bootstrap.memory_lock=truelist
      - xpack.security.enabled=false
      - discovery.type=single-node
    mem_limit: "3221225472"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elastic
    healthcheck:
       test: curl -s http://es01:9200 >/dev/null || exit 1
       interval: 30s
       timeout: 10s
       retries: 50
    # healthcheck:
    #   test:
    #     [
    #       "CMD-SHELL",
    #       "curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q 'missing authentication credentials'",
    #     ]
    #   interval: 10s
    #   timeout: 10s
    #   retries: 120

  kibana:
    image: repo-nexus.kavosh.org:8080/kibana:8.7.1
    container_name: kibana
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      # - certs:/usr/share/kibana/config/certs
      - /data/kibana/data:/usr/share/kibana/data
    ports:
      - 5601:5601
    environment:
      - SERVERNAME=kibana
      - ELASTICSEARCH_HOSTS=http://es01:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}
    mem_limit: "3221225472"
    healthcheck:
       test: curl -s http://kibana:5601 >/dev/null || exit 1
       interval: 30s
       timeout: 10s
       retries: 50
    # healthcheck:
    #   test:
    #     [
    #       "CMD-SHELL",
    #       "curl -s -I http://localhost:5601 | grep -q 'HTTP/1.1 302 Found'",
    #     ]
    #   interval: 10s
    #   timeout: 10s
    #   retries: 120
    networks:
      - elastic

  filebeat:
    # build:
    #   context: filebeat
    #   dockerfile: filebeat-Dockerfile
    image: repo-nexus.kavosh.org:8080/elastic/filebeat:8.7.1
    container_name: filebeat
    user: root
    volumes:
      - /etc/localtime:/etc/localtime:ro
# DOCKER
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
# FileBeat Config
      - /data/filebeat/data:/usr/share/filebeat/data
      - /data/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /data/filebeat/ingest_data/:/usr/share/filebeat/ingest_data/
# Modules
      - /data/filebeat/modules.d/fortinet.yml:/usr/share/filebeat/modules.d/fortinet.yml:ro     # FortiNet
# Static Files
      - /srv/docker-composes/nginx/logs/nginx:/var/log/nginx:ro   # NGINX
# Certs
      # - certs:/usr/share/filebeat/certs

    ports:
      - 514:9004
      - 514:9004/udp
    environment:
      - ELASTIC_USER=${ELASTIC_USER}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - ELASTIC_HOSTS=http://es01:9200
      - KIBANA_HOSTS=http://kibana:5601
      # - LOGSTASH_HOSTS=http://logstash01:9600
    healthcheck:
       test: curl -s http://filebeat >/dev/null || exit 1
       interval: 30s
       timeout: 10s
       retries: 50
    networks:
      - elastic

networks:
  elastic:
    external: true
    name: elastic
